### ISSUE TITLE
Include "tags" into the figma library file to make search easier

### ISSUE THREAD

**Issue by Simon-Renault** [phosphor-icons/figma#12]
it would be amazing to include "Tags" into the description of each Icon in the figma library. 

It would make searching for Icons so much easier !

<img width="394" alt="Screenshot 2022-10-16 at 15 00 21" src="https://user-images.githubusercontent.com/30470644/196039655-5d05e032-6b4b-4db5-9858-c78eff21db08.png">

**Comment by rektdeckard** [comment]
Coming soon...

**Comment by rektdeckard** [comment]
Included in v2.0.0
